openapi: 3.0.3
info:
  title: Customer Service API
  version: 1.0.0
  description: Microservice customers

servers:
  - url: http://localhost:8081
    description: Local server

paths:
  /api/v1/customers:
    get:
      summary: Get all customers
      operationId: getAllCustomers
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClientResponse'

    post:
      summary: Create a new customer
      operationId: createCustomer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClientRequest'
      responses:
        '201':
          description: Customer created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientResponse'
        '400':
          description: Bad request

  /api/v1/customers/{id}:
    get:
      summary: Get customer by ID
      operationId: getCustomerById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientResponse'
        '404':
          description: Customer not found

    put:
      summary: Update customer
      operationId: updateCustomer
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClientRequest'
      responses:
        '200':
          description: Customer updated

    delete:
      summary: Delete customer
      operationId: deleteCustomer
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Customer deleted

components:
  schemas:
    ClientRequest:
      type: object
      required:
        - name
        - gender
        - identification
        - address
        - phone
        - password
      properties:
        name:
          type: string
          example: "Jose Lema"
        gender:
          type: string
          example: "M"
        identification:
          type: string
          example: "1234567890"
        address:
          type: string
          example: "Otavalo sn y principal"
        phone:
          type: string
          example: "098254785"
        password:
          type: string
          example: "1234"
        status:
          type: boolean
          default: true

    ClientResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        gender:
          type: string
        identification:
          type: string
        address:
          type: string
        phone:
          type: string
        status:
          type: boolean